#!/usr/bin/env python3

# here add you interface name (most probably wlan0)
interface = "wlp0s20f0u1"

from os import popen
from time import sleep

temp_conti = str(popen("grep {} /proc/net/dev".format(interface)).read().rstrip()).split(" ")
conti = []
for item in temp_conti:
    if str(item) != "":
        conti.append(item)

sleep(0.9999)

temp_contf = str(popen("grep {} /proc/net/dev".format(interface)).read().rstrip()).split(" ")
contf = []
for item in temp_contf:
    if str(item) != "":
        contf.append(item)

d_diff = int(contf[1]) - int(conti[1])
u_diff = int(contf[9]) - int(conti[9])

print("D:{}|U:{}".format(round(d_diff/1024/1024, 3), round(u_diff/1024/1024, 3)))

